name: HiveBox CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    ci-pipeline:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install python lint tools
              run: |
                pip install flake8

            - name: Lint Python code with flake8
              run: flake8 HiveBox.py

            - name: Lint Dockerfile with hadolint
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile

            - name: Build Docker image
              run: docker build -t hivebox:0.0.2 .

            - name: Run Docker container
              run: |
                docker run -d -p 5000:5000 --name hivebox hivebox:0.0.2
                sleep 5

            - name: Test /version endpoint
              run: |
                response=$(curl -s http://127.0.0.1:5000/version | jq -r '.version')
                if [ "$response" != "v0.0.2" ]; then
                  echo "Version mismatch! Expected v0.0.2 but got $response"
                  exit 1
                fi
                echo "/version endpoint returned: $response"